{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}


module Biatob.Proto.Mvp exposing
    ( TradeState(..), Void(..), Resolution(..), PredictionViewPrivacy(..), PredictionFollowingStatus(..), AuthToken, EmailFlowStateKind(..), EmailFlowState, EmailFlowStateCodeSent, HashedPassword, LoginType(..), GenericUserInfo, GenericUserInfoInvitation, Relationship, UsernameInfo, EmailAttempt, ResolutionEventPriorRevision(..), ResolutionEvent, Trade, Empty, ErrorResponse, WhoamiRequest, WhoamiResponse, SignOutRequest, SignOutResponse, AuthSuccess, SendVerificationEmailRequest, RegisterUsernameRequest, LogInUsernameRequest, CertaintyRange, CreatePredictionRequest, CreatePredictionResponse, GetPredictionRequest, UserPredictionView, ListMyStakesRequest, PredictionsById, ListPredictionsRequest, FollowRequest, StakeRequest, ResolveRequest, SetTrustedRequest, GetUserRequest, ChangePasswordRequest, GetSettingsRequest, SendInvitationRequest, CheckInvitationRequest, CheckInvitationResponse, AcceptInvitationRequest, SavedCreatedPredictionFormState
    , authTokenDecoder, emailFlowStateDecoder, hashedPasswordDecoder, genericUserInfoDecoder, relationshipDecoder, usernameInfoDecoder, emailAttemptDecoder, resolutionEventDecoder, tradeDecoder, emptyDecoder, errorResponseDecoder, whoamiRequestDecoder, whoamiResponseDecoder, signOutRequestDecoder, signOutResponseDecoder, authSuccessDecoder, sendVerificationEmailRequestDecoder, registerUsernameRequestDecoder, logInUsernameRequestDecoder, certaintyRangeDecoder, createPredictionRequestDecoder, createPredictionResponseDecoder, getPredictionRequestDecoder, userPredictionViewDecoder, listMyStakesRequestDecoder, predictionsByIdDecoder, listPredictionsRequestDecoder, followRequestDecoder, stakeRequestDecoder, resolveRequestDecoder, setTrustedRequestDecoder, getUserRequestDecoder, changePasswordRequestDecoder, getSettingsRequestDecoder, sendInvitationRequestDecoder, checkInvitationRequestDecoder, checkInvitationResponseDecoder, acceptInvitationRequestDecoder, savedCreatedPredictionFormStateDecoder
    , toAuthTokenEncoder, toEmailFlowStateEncoder, toHashedPasswordEncoder, toGenericUserInfoEncoder, toRelationshipEncoder, toUsernameInfoEncoder, toEmailAttemptEncoder, toResolutionEventEncoder, toTradeEncoder, toEmptyEncoder, toErrorResponseEncoder, toWhoamiRequestEncoder, toWhoamiResponseEncoder, toSignOutRequestEncoder, toSignOutResponseEncoder, toAuthSuccessEncoder, toSendVerificationEmailRequestEncoder, toRegisterUsernameRequestEncoder, toLogInUsernameRequestEncoder, toCertaintyRangeEncoder, toCreatePredictionRequestEncoder, toCreatePredictionResponseEncoder, toGetPredictionRequestEncoder, toUserPredictionViewEncoder, toListMyStakesRequestEncoder, toPredictionsByIdEncoder, toListPredictionsRequestEncoder, toFollowRequestEncoder, toStakeRequestEncoder, toResolveRequestEncoder, toSetTrustedRequestEncoder, toGetUserRequestEncoder, toChangePasswordRequestEncoder, toGetSettingsRequestEncoder, toSendInvitationRequestEncoder, toCheckInvitationRequestEncoder, toCheckInvitationResponseEncoder, toAcceptInvitationRequestEncoder, toSavedCreatedPredictionFormStateEncoder
    )

{-| ProtoBuf module: `Biatob.Proto.Mvp`

This module was generated automatically using

  - [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 1.0.0-beta-2
  - `protoc` 3.14.0
  - the following specification file: `protobuf/mvp.proto`

To run it use [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.1.0) version 1.1.0 or higher.


# Model

@docs TradeState, Void, Resolution, PredictionViewPrivacy, PredictionFollowingStatus, AuthToken, EmailFlowStateKind, EmailFlowState, EmailFlowStateCodeSent, HashedPassword, LoginType, GenericUserInfo, GenericUserInfoInvitation, Relationship, UsernameInfo, EmailAttempt, ResolutionEventPriorRevision, ResolutionEvent, Trade, Empty, ErrorResponse, WhoamiRequest, WhoamiResponse, SignOutRequest, SignOutResponse, AuthSuccess, SendVerificationEmailRequest, RegisterUsernameRequest, LogInUsernameRequest, CertaintyRange, CreatePredictionRequest, CreatePredictionResponse, GetPredictionRequest, UserPredictionView, ListMyStakesRequest, PredictionsById, ListPredictionsRequest, FollowRequest, StakeRequest, ResolveRequest, SetTrustedRequest, GetUserRequest, ChangePasswordRequest, GetSettingsRequest, SendInvitationRequest, CheckInvitationRequest, CheckInvitationResponse, AcceptInvitationRequest, SavedCreatedPredictionFormState


# Decoder

@docs authTokenDecoder, emailFlowStateDecoder, hashedPasswordDecoder, genericUserInfoDecoder, relationshipDecoder, usernameInfoDecoder, emailAttemptDecoder, resolutionEventDecoder, tradeDecoder, emptyDecoder, errorResponseDecoder, whoamiRequestDecoder, whoamiResponseDecoder, signOutRequestDecoder, signOutResponseDecoder, authSuccessDecoder, sendVerificationEmailRequestDecoder, registerUsernameRequestDecoder, logInUsernameRequestDecoder, certaintyRangeDecoder, createPredictionRequestDecoder, createPredictionResponseDecoder, getPredictionRequestDecoder, userPredictionViewDecoder, listMyStakesRequestDecoder, predictionsByIdDecoder, listPredictionsRequestDecoder, followRequestDecoder, stakeRequestDecoder, resolveRequestDecoder, setTrustedRequestDecoder, getUserRequestDecoder, changePasswordRequestDecoder, getSettingsRequestDecoder, sendInvitationRequestDecoder, checkInvitationRequestDecoder, checkInvitationResponseDecoder, acceptInvitationRequestDecoder, savedCreatedPredictionFormStateDecoder


# Encoder

@docs toAuthTokenEncoder, toEmailFlowStateEncoder, toHashedPasswordEncoder, toGenericUserInfoEncoder, toRelationshipEncoder, toUsernameInfoEncoder, toEmailAttemptEncoder, toResolutionEventEncoder, toTradeEncoder, toEmptyEncoder, toErrorResponseEncoder, toWhoamiRequestEncoder, toWhoamiResponseEncoder, toSignOutRequestEncoder, toSignOutResponseEncoder, toAuthSuccessEncoder, toSendVerificationEmailRequestEncoder, toRegisterUsernameRequestEncoder, toLogInUsernameRequestEncoder, toCertaintyRangeEncoder, toCreatePredictionRequestEncoder, toCreatePredictionResponseEncoder, toGetPredictionRequestEncoder, toUserPredictionViewEncoder, toListMyStakesRequestEncoder, toPredictionsByIdEncoder, toListPredictionsRequestEncoder, toFollowRequestEncoder, toStakeRequestEncoder, toResolveRequestEncoder, toSetTrustedRequestEncoder, toGetUserRequestEncoder, toChangePasswordRequestEncoder, toGetSettingsRequestEncoder, toSendInvitationRequestEncoder, toCheckInvitationRequestEncoder, toCheckInvitationResponseEncoder, toAcceptInvitationRequestEncoder, toSavedCreatedPredictionFormStateEncoder

-}

import Bytes
import Dict
import Protobuf.Decode as Decode
import Protobuf.Encode as Encode



-- MODEL


{-| `TradeState` enumeration
-}
type TradeState
    = TradeStateActive
    | TradeStateQueued
    | TradeStateDisavowed
    | TradeStateDequeueFailed
    | TradeStateUnrecognized_ Int


{-| `Void` enumeration
-}
type Void
    = Void
    | VoidUnrecognized_ Int


{-| `Resolution` enumeration
-}
type Resolution
    = ResolutionNoneYet
    | ResolutionYes
    | ResolutionNo
    | ResolutionInvalid
    | ResolutionUnrecognized_ Int


{-| `PredictionViewPrivacy` enumeration
-}
type PredictionViewPrivacy
    = PredictionViewPrivacyAnybody
    | PredictionViewPrivacyAnybodyWithTheLink
    | PredictionViewPrivacyUnrecognized_ Int


{-| `PredictionFollowingStatus` enumeration
-}
type PredictionFollowingStatus
    = PredictionFollowingNotFollowing
    | PredictionFollowingFollowing
    | PredictionFollowingMandatoryBecauseStaked
    | PredictionFollowingStatusUnrecognized_ Int


{-| `AuthToken` message
-}
type alias AuthToken =
    { hmacOfRest : Bytes.Bytes
    , owner : String
    , mintedUnixtime : Float
    , expiresUnixtime : Float
    }


{-| EmailFlowStateKind
-}
type EmailFlowStateKind
    = EmailFlowStateKindUnstarted Void
    | EmailFlowStateKindCodeSent EmailFlowStateCodeSent
    | EmailFlowStateKindVerified String


{-| `EmailFlowState` message
-}
type alias EmailFlowState =
    { emailFlowStateKind : Maybe EmailFlowStateKind
    }


{-| `EmailFlowStateCodeSent` message
-}
type alias EmailFlowStateCodeSent =
    { email : String
    , code : Maybe HashedPassword
    }


{-| `HashedPassword` message
-}
type alias HashedPassword =
    { salt : Bytes.Bytes
    , scrypt : Bytes.Bytes
    }


{-| LoginType
-}
type LoginType
    = LoginTypeLoginPassword HashedPassword


{-| `GenericUserInfo` message
-}
type alias GenericUserInfo =
    { emailAddress : String
    , invitations : Dict.Dict String (Maybe GenericUserInfoInvitation)
    , relationships : Dict.Dict String (Maybe Relationship)
    , loginType : Maybe LoginType
    }


{-| `GenericUserInfoInvitation` message
-}
type alias GenericUserInfoInvitation =
    {}


{-| `Relationship` message
-}
type alias Relationship =
    { trustsYou : Bool
    , trustedByYou : Bool
    }


{-| `UsernameInfo` message
-}
type alias UsernameInfo =
    { info : Maybe GenericUserInfo
    , password : Maybe HashedPassword
    }


{-| `EmailAttempt` message
-}
type alias EmailAttempt =
    { unixtime : Float
    , succeeded : Bool
    }


{-| ResolutionEventPriorRevision
-}
type ResolutionEventPriorRevision
    = ResolutionEventPriorRevision (Maybe ResolutionEvent)


{-| `ResolutionEvent` message
-}
type alias ResolutionEvent =
    { unixtime : Float
    , resolution : Resolution
    , notes : String
    , priorRevision : ResolutionEventPriorRevision
    }


{-| `Trade` message
-}
type alias Trade =
    { bettor : String
    , bettorIsASkeptic : Bool
    , bettorStakeCents : Int
    , creatorStakeCents : Int
    , transactedUnixtime : Float
    , updatedUnixtime : Float
    , notes : String
    , state : TradeState
    }


{-| `Empty` message
-}
type alias Empty =
    {}


{-| `ErrorResponse` message
-}
type alias ErrorResponse =
    { catchall : String
    }


{-| `WhoamiRequest` message
-}
type alias WhoamiRequest =
    {}


{-| `WhoamiResponse` message
-}
type alias WhoamiResponse =
    { username : String
    }


{-| `SignOutRequest` message
-}
type alias SignOutRequest =
    {}


{-| `SignOutResponse` message
-}
type alias SignOutResponse =
    {}


{-| `AuthSuccess` message
-}
type alias AuthSuccess =
    { token : Maybe AuthToken
    , userInfo : Maybe GenericUserInfo
    }


{-| `SendVerificationEmailRequest` message
-}
type alias SendVerificationEmailRequest =
    { emailAddress : String
    }


{-| `RegisterUsernameRequest` message
-}
type alias RegisterUsernameRequest =
    { username : String
    , password : String
    , proofOfEmailToken : String
    }


{-| `LogInUsernameRequest` message
-}
type alias LogInUsernameRequest =
    { username : String
    , password : String
    }


{-| `CertaintyRange` message
-}
type alias CertaintyRange =
    { low : Float
    , high : Float
    }


{-| `CreatePredictionRequest` message
-}
type alias CreatePredictionRequest =
    { prediction : String
    , viewPrivacy : PredictionViewPrivacy
    , certainty : Maybe CertaintyRange
    , maximumStakeCents : Int
    , openSeconds : Int
    , specialRules : String
    , resolvesAtUnixtime : Float
    }


{-| `CreatePredictionResponse` message
-}
type alias CreatePredictionResponse =
    { newPredictionId : String
    }


{-| `GetPredictionRequest` message
-}
type alias GetPredictionRequest =
    { predictionId : String
    }


{-| `UserPredictionView` message
-}
type alias UserPredictionView =
    { prediction : String
    , certainty : Maybe CertaintyRange
    , maximumStakeCents : Int
    , remainingStakeCentsVsBelievers : Int
    , remainingStakeCentsVsSkeptics : Int
    , createdUnixtime : Float
    , closesUnixtime : Float
    , specialRules : String
    , creator : String
    , resolution : Maybe ResolutionEvent
    , yourTrades : List Trade
    , resolvesAtUnixtime : Float
    , yourFollowingStatus : PredictionFollowingStatus
    }


{-| `ListMyStakesRequest` message
-}
type alias ListMyStakesRequest =
    {}


{-| `PredictionsById` message
-}
type alias PredictionsById =
    { predictions : Dict.Dict String (Maybe UserPredictionView)
    }


{-| `ListPredictionsRequest` message
-}
type alias ListPredictionsRequest =
    { creator : String
    }


{-| `FollowRequest` message
-}
type alias FollowRequest =
    { predictionId : String
    , follow : Bool
    }


{-| `StakeRequest` message
-}
type alias StakeRequest =
    { predictionId : String
    , bettorIsASkeptic : Bool
    , bettorStakeCents : Int
    }


{-| `ResolveRequest` message
-}
type alias ResolveRequest =
    { predictionId : String
    , resolution : Resolution
    , notes : String
    }


{-| `SetTrustedRequest` message
-}
type alias SetTrustedRequest =
    { who : String
    , trusted : Bool
    }


{-| `GetUserRequest` message
-}
type alias GetUserRequest =
    { who : String
    }


{-| `ChangePasswordRequest` message
-}
type alias ChangePasswordRequest =
    { oldPassword : String
    , newPassword : String
    }


{-| `GetSettingsRequest` message
-}
type alias GetSettingsRequest =
    { includeRelationshipsWithUsers : List String
    }


{-| `SendInvitationRequest` message
-}
type alias SendInvitationRequest =
    { recipient : String
    }


{-| `CheckInvitationRequest` message
-}
type alias CheckInvitationRequest =
    { nonce : String
    }


{-| `CheckInvitationResponse` message
-}
type alias CheckInvitationResponse =
    { inviter : String
    , recipient : String
    }


{-| `AcceptInvitationRequest` message
-}
type alias AcceptInvitationRequest =
    { nonce : String
    }


{-| `SavedCreatedPredictionFormState` message
-}
type alias SavedCreatedPredictionFormState =
    { predictionField : String
    , resolvesAtField : String
    , stakeField : String
    , lowPField : String
    , highPField : String
    , openForUnitField : String
    , openForSecondsField : String
    , viewPrivacyField : String
    , specialRulesField : String
    }



-- DECODER


tradeStateDecoder : Decode.Decoder TradeState
tradeStateDecoder =
    Decode.int32
        |> Decode.map
            (\value ->
                case value of
                    0 ->
                        TradeStateActive

                    1 ->
                        TradeStateQueued

                    2 ->
                        TradeStateDisavowed

                    3 ->
                        TradeStateDequeueFailed

                    v ->
                        TradeStateUnrecognized_ v
            )


voidDecoder : Decode.Decoder Void
voidDecoder =
    Decode.int32
        |> Decode.map
            (\value ->
                case value of
                    0 ->
                        Void

                    v ->
                        VoidUnrecognized_ v
            )


resolutionDecoder : Decode.Decoder Resolution
resolutionDecoder =
    Decode.int32
        |> Decode.map
            (\value ->
                case value of
                    0 ->
                        ResolutionNoneYet

                    1 ->
                        ResolutionYes

                    2 ->
                        ResolutionNo

                    3 ->
                        ResolutionInvalid

                    v ->
                        ResolutionUnrecognized_ v
            )


predictionViewPrivacyDecoder : Decode.Decoder PredictionViewPrivacy
predictionViewPrivacyDecoder =
    Decode.int32
        |> Decode.map
            (\value ->
                case value of
                    0 ->
                        PredictionViewPrivacyAnybody

                    1 ->
                        PredictionViewPrivacyAnybodyWithTheLink

                    v ->
                        PredictionViewPrivacyUnrecognized_ v
            )


predictionFollowingStatusDecoder : Decode.Decoder PredictionFollowingStatus
predictionFollowingStatusDecoder =
    Decode.int32
        |> Decode.map
            (\value ->
                case value of
                    0 ->
                        PredictionFollowingNotFollowing

                    1 ->
                        PredictionFollowingFollowing

                    2 ->
                        PredictionFollowingMandatoryBecauseStaked

                    v ->
                        PredictionFollowingStatusUnrecognized_ v
            )


{-| `AuthToken` decoder
-}
authTokenDecoder : Decode.Decoder AuthToken
authTokenDecoder =
    Decode.message (AuthToken (Encode.encode <| Encode.string "") "" 0 0)
        [ Decode.optional 1 Decode.bytes setHmacOfRest
        , Decode.optional 7 Decode.string setOwner
        , Decode.optional 5 Decode.double setMintedUnixtime
        , Decode.optional 6 Decode.double setExpiresUnixtime
        ]


{-| `EmailFlowState` decoder
-}
emailFlowStateDecoder : Decode.Decoder EmailFlowState
emailFlowStateDecoder =
    Decode.message (EmailFlowState Nothing)
        [ Decode.oneOf
            [ ( 1, Decode.map EmailFlowStateKindUnstarted voidDecoder )
            , ( 2, Decode.map EmailFlowStateKindCodeSent emailFlowStateCodeSentDecoder )
            , ( 3, Decode.map EmailFlowStateKindVerified Decode.string )
            ]
            setEmailFlowStateKind
        ]


emailFlowStateCodeSentDecoder : Decode.Decoder EmailFlowStateCodeSent
emailFlowStateCodeSentDecoder =
    Decode.message (EmailFlowStateCodeSent "" Nothing)
        [ Decode.optional 1 Decode.string setEmail
        , Decode.optional 2 (Decode.map Just hashedPasswordDecoder) setCode
        ]


{-| `HashedPassword` decoder
-}
hashedPasswordDecoder : Decode.Decoder HashedPassword
hashedPasswordDecoder =
    Decode.message (HashedPassword (Encode.encode <| Encode.string "") (Encode.encode <| Encode.string ""))
        [ Decode.optional 1 Decode.bytes setSalt
        , Decode.optional 2 Decode.bytes setScrypt
        ]


{-| `GenericUserInfo` decoder
-}
genericUserInfoDecoder : Decode.Decoder GenericUserInfo
genericUserInfoDecoder =
    Decode.message (GenericUserInfo "" Dict.empty Dict.empty Nothing)
        [ Decode.optional 10 Decode.string setEmailAddress
        , Decode.mapped 5 ( "", Nothing ) Decode.string (Decode.map Just genericUserInfoInvitationDecoder) .invitations setInvitations
        , Decode.mapped 6 ( "", Nothing ) Decode.string (Decode.map Just relationshipDecoder) .relationships setRelationships
        , Decode.oneOf
            [ ( 7, Decode.map LoginTypeLoginPassword hashedPasswordDecoder )
            ]
            setLoginType
        ]


genericUserInfoInvitationDecoder : Decode.Decoder GenericUserInfoInvitation
genericUserInfoInvitationDecoder =
    Decode.message GenericUserInfoInvitation
        []


{-| `Relationship` decoder
-}
relationshipDecoder : Decode.Decoder Relationship
relationshipDecoder =
    Decode.message (Relationship False False)
        [ Decode.optional 1 Decode.bool setTrustsYou
        , Decode.optional 2 Decode.bool setTrustedByYou
        ]


{-| `UsernameInfo` decoder
-}
usernameInfoDecoder : Decode.Decoder UsernameInfo
usernameInfoDecoder =
    Decode.message (UsernameInfo Nothing Nothing)
        [ Decode.optional 1 (Decode.map Just genericUserInfoDecoder) setInfo
        , Decode.optional 2 (Decode.map Just hashedPasswordDecoder) setPassword
        ]


{-| `EmailAttempt` decoder
-}
emailAttemptDecoder : Decode.Decoder EmailAttempt
emailAttemptDecoder =
    Decode.message (EmailAttempt 0 False)
        [ Decode.optional 1 Decode.double setUnixtime
        , Decode.optional 2 Decode.bool setSucceeded
        ]


unwrapResolutionEventPriorRevision : ResolutionEventPriorRevision -> Maybe ResolutionEvent
unwrapResolutionEventPriorRevision (ResolutionEventPriorRevision value) =
    value


{-| `ResolutionEvent` decoder
-}
resolutionEventDecoder : Decode.Decoder ResolutionEvent
resolutionEventDecoder =
    Decode.message (ResolutionEvent 0 ResolutionNoneYet "" (ResolutionEventPriorRevision Nothing))
        [ Decode.optional 4 Decode.double setUnixtime
        , Decode.optional 2 resolutionDecoder setResolution
        , Decode.optional 3 Decode.string setNotes
        , Decode.optional 5 (Decode.lazy (\_ -> (Decode.map Just resolutionEventDecoder))) (setPriorRevision << ResolutionEventPriorRevision)
        ]


{-| `Trade` decoder
-}
tradeDecoder : Decode.Decoder Trade
tradeDecoder =
    Decode.message (Trade "" False 0 0 0 0 "" TradeStateActive)
        [ Decode.optional 7 Decode.string setBettor
        , Decode.optional 2 Decode.bool setBettorIsASkeptic
        , Decode.optional 3 Decode.uint32 setBettorStakeCents
        , Decode.optional 4 Decode.uint32 setCreatorStakeCents
        , Decode.optional 6 Decode.double setTransactedUnixtime
        , Decode.optional 8 Decode.double setUpdatedUnixtime
        , Decode.optional 9 Decode.string setNotes
        , Decode.optional 10 tradeStateDecoder setState
        ]


{-| `Empty` decoder
-}
emptyDecoder : Decode.Decoder Empty
emptyDecoder =
    Decode.message Empty
        []


{-| `ErrorResponse` decoder
-}
errorResponseDecoder : Decode.Decoder ErrorResponse
errorResponseDecoder =
    Decode.message (ErrorResponse "")
        [ Decode.optional 1 Decode.string setCatchall
        ]


{-| `WhoamiRequest` decoder
-}
whoamiRequestDecoder : Decode.Decoder WhoamiRequest
whoamiRequestDecoder =
    Decode.message WhoamiRequest
        []


{-| `WhoamiResponse` decoder
-}
whoamiResponseDecoder : Decode.Decoder WhoamiResponse
whoamiResponseDecoder =
    Decode.message (WhoamiResponse "")
        [ Decode.optional 1 Decode.string setUsername
        ]


{-| `SignOutRequest` decoder
-}
signOutRequestDecoder : Decode.Decoder SignOutRequest
signOutRequestDecoder =
    Decode.message SignOutRequest
        []


{-| `SignOutResponse` decoder
-}
signOutResponseDecoder : Decode.Decoder SignOutResponse
signOutResponseDecoder =
    Decode.message SignOutResponse
        []


{-| `AuthSuccess` decoder
-}
authSuccessDecoder : Decode.Decoder AuthSuccess
authSuccessDecoder =
    Decode.message (AuthSuccess Nothing Nothing)
        [ Decode.optional 1 (Decode.map Just authTokenDecoder) setToken
        , Decode.optional 2 (Decode.map Just genericUserInfoDecoder) setUserInfo
        ]


{-| `SendVerificationEmailRequest` decoder
-}
sendVerificationEmailRequestDecoder : Decode.Decoder SendVerificationEmailRequest
sendVerificationEmailRequestDecoder =
    Decode.message (SendVerificationEmailRequest "")
        [ Decode.optional 1 Decode.string setEmailAddress
        ]


{-| `RegisterUsernameRequest` decoder
-}
registerUsernameRequestDecoder : Decode.Decoder RegisterUsernameRequest
registerUsernameRequestDecoder =
    Decode.message (RegisterUsernameRequest "" "" "")
        [ Decode.optional 1 Decode.string setUsername
        , Decode.optional 2 Decode.string setPassword
        , Decode.optional 3 Decode.string setProofOfEmailToken
        ]


{-| `LogInUsernameRequest` decoder
-}
logInUsernameRequestDecoder : Decode.Decoder LogInUsernameRequest
logInUsernameRequestDecoder =
    Decode.message (LogInUsernameRequest "" "")
        [ Decode.optional 1 Decode.string setUsername
        , Decode.optional 2 Decode.string setPassword
        ]


{-| `CertaintyRange` decoder
-}
certaintyRangeDecoder : Decode.Decoder CertaintyRange
certaintyRangeDecoder =
    Decode.message (CertaintyRange 0 0)
        [ Decode.optional 1 Decode.float setLow
        , Decode.optional 2 Decode.float setHigh
        ]


{-| `CreatePredictionRequest` decoder
-}
createPredictionRequestDecoder : Decode.Decoder CreatePredictionRequest
createPredictionRequestDecoder =
    Decode.message (CreatePredictionRequest "" PredictionViewPrivacyAnybody Nothing 0 0 "" 0)
        [ Decode.optional 2 Decode.string setPrediction
        , Decode.optional 3 predictionViewPrivacyDecoder setViewPrivacy
        , Decode.optional 4 (Decode.map Just certaintyRangeDecoder) setCertainty
        , Decode.optional 5 Decode.uint32 setMaximumStakeCents
        , Decode.optional 6 Decode.uint32 setOpenSeconds
        , Decode.optional 7 Decode.string setSpecialRules
        , Decode.optional 9 Decode.double setResolvesAtUnixtime
        ]


{-| `CreatePredictionResponse` decoder
-}
createPredictionResponseDecoder : Decode.Decoder CreatePredictionResponse
createPredictionResponseDecoder =
    Decode.message (CreatePredictionResponse "")
        [ Decode.optional 1 Decode.string setNewPredictionId
        ]


{-| `GetPredictionRequest` decoder
-}
getPredictionRequestDecoder : Decode.Decoder GetPredictionRequest
getPredictionRequestDecoder =
    Decode.message (GetPredictionRequest "")
        [ Decode.optional 2 Decode.string setPredictionId
        ]


{-| `UserPredictionView` decoder
-}
userPredictionViewDecoder : Decode.Decoder UserPredictionView
userPredictionViewDecoder =
    Decode.message (UserPredictionView "" Nothing 0 0 0 0 0 "" "" Nothing [] 0 PredictionFollowingNotFollowing)
        [ Decode.optional 1 Decode.string setPrediction
        , Decode.optional 2 (Decode.map Just certaintyRangeDecoder) setCertainty
        , Decode.optional 3 Decode.uint32 setMaximumStakeCents
        , Decode.optional 4 Decode.uint32 setRemainingStakeCentsVsBelievers
        , Decode.optional 5 Decode.uint32 setRemainingStakeCentsVsSkeptics
        , Decode.optional 13 Decode.double setCreatedUnixtime
        , Decode.optional 14 Decode.double setClosesUnixtime
        , Decode.optional 8 Decode.string setSpecialRules
        , Decode.optional 9 Decode.string setCreator
        , Decode.optional 17 (Decode.map Just resolutionEventDecoder) setResolution
        , Decode.repeated 11 tradeDecoder .yourTrades setYourTrades
        , Decode.optional 15 Decode.double setResolvesAtUnixtime
        , Decode.optional 18 predictionFollowingStatusDecoder setYourFollowingStatus
        ]


{-| `ListMyStakesRequest` decoder
-}
listMyStakesRequestDecoder : Decode.Decoder ListMyStakesRequest
listMyStakesRequestDecoder =
    Decode.message ListMyStakesRequest
        []


{-| `PredictionsById` decoder
-}
predictionsByIdDecoder : Decode.Decoder PredictionsById
predictionsByIdDecoder =
    Decode.message (PredictionsById Dict.empty)
        [ Decode.mapped 1 ( "", Nothing ) Decode.string (Decode.map Just userPredictionViewDecoder) .predictions setPredictions
        ]


{-| `ListPredictionsRequest` decoder
-}
listPredictionsRequestDecoder : Decode.Decoder ListPredictionsRequest
listPredictionsRequestDecoder =
    Decode.message (ListPredictionsRequest "")
        [ Decode.optional 2 Decode.string setCreator
        ]


{-| `FollowRequest` decoder
-}
followRequestDecoder : Decode.Decoder FollowRequest
followRequestDecoder =
    Decode.message (FollowRequest "" False)
        [ Decode.optional 1 Decode.string setPredictionId
        , Decode.optional 2 Decode.bool setFollow
        ]


{-| `StakeRequest` decoder
-}
stakeRequestDecoder : Decode.Decoder StakeRequest
stakeRequestDecoder =
    Decode.message (StakeRequest "" False 0)
        [ Decode.optional 2 Decode.string setPredictionId
        , Decode.optional 3 Decode.bool setBettorIsASkeptic
        , Decode.optional 4 Decode.uint32 setBettorStakeCents
        ]


{-| `ResolveRequest` decoder
-}
resolveRequestDecoder : Decode.Decoder ResolveRequest
resolveRequestDecoder =
    Decode.message (ResolveRequest "" ResolutionNoneYet "")
        [ Decode.optional 1 Decode.string setPredictionId
        , Decode.optional 2 resolutionDecoder setResolution
        , Decode.optional 3 Decode.string setNotes
        ]


{-| `SetTrustedRequest` decoder
-}
setTrustedRequestDecoder : Decode.Decoder SetTrustedRequest
setTrustedRequestDecoder =
    Decode.message (SetTrustedRequest "" False)
        [ Decode.optional 3 Decode.string setWho
        , Decode.optional 2 Decode.bool setTrusted
        ]


{-| `GetUserRequest` decoder
-}
getUserRequestDecoder : Decode.Decoder GetUserRequest
getUserRequestDecoder =
    Decode.message (GetUserRequest "")
        [ Decode.optional 2 Decode.string setWho
        ]


{-| `ChangePasswordRequest` decoder
-}
changePasswordRequestDecoder : Decode.Decoder ChangePasswordRequest
changePasswordRequestDecoder =
    Decode.message (ChangePasswordRequest "" "")
        [ Decode.optional 1 Decode.string setOldPassword
        , Decode.optional 2 Decode.string setNewPassword
        ]


{-| `GetSettingsRequest` decoder
-}
getSettingsRequestDecoder : Decode.Decoder GetSettingsRequest
getSettingsRequestDecoder =
    Decode.message (GetSettingsRequest [])
        [ Decode.repeated 1 Decode.string .includeRelationshipsWithUsers setIncludeRelationshipsWithUsers
        ]


{-| `SendInvitationRequest` decoder
-}
sendInvitationRequestDecoder : Decode.Decoder SendInvitationRequest
sendInvitationRequestDecoder =
    Decode.message (SendInvitationRequest "")
        [ Decode.optional 1 Decode.string setRecipient
        ]


{-| `CheckInvitationRequest` decoder
-}
checkInvitationRequestDecoder : Decode.Decoder CheckInvitationRequest
checkInvitationRequestDecoder =
    Decode.message (CheckInvitationRequest "")
        [ Decode.optional 1 Decode.string setNonce
        ]


{-| `CheckInvitationResponse` decoder
-}
checkInvitationResponseDecoder : Decode.Decoder CheckInvitationResponse
checkInvitationResponseDecoder =
    Decode.message (CheckInvitationResponse "" "")
        [ Decode.optional 1 Decode.string setInviter
        , Decode.optional 2 Decode.string setRecipient
        ]


{-| `AcceptInvitationRequest` decoder
-}
acceptInvitationRequestDecoder : Decode.Decoder AcceptInvitationRequest
acceptInvitationRequestDecoder =
    Decode.message (AcceptInvitationRequest "")
        [ Decode.optional 1 Decode.string setNonce
        ]


{-| `SavedCreatedPredictionFormState` decoder
-}
savedCreatedPredictionFormStateDecoder : Decode.Decoder SavedCreatedPredictionFormState
savedCreatedPredictionFormStateDecoder =
    Decode.message (SavedCreatedPredictionFormState "" "" "" "" "" "" "" "" "")
        [ Decode.optional 1 Decode.string setPredictionField
        , Decode.optional 2 Decode.string setResolvesAtField
        , Decode.optional 3 Decode.string setStakeField
        , Decode.optional 4 Decode.string setLowPField
        , Decode.optional 5 Decode.string setHighPField
        , Decode.optional 6 Decode.string setOpenForUnitField
        , Decode.optional 7 Decode.string setOpenForSecondsField
        , Decode.optional 9 Decode.string setViewPrivacyField
        , Decode.optional 8 Decode.string setSpecialRulesField
        ]



-- ENCODER


toTradeStateEncoder : TradeState -> Encode.Encoder
toTradeStateEncoder value =
    Encode.int32 <|
        case value of
            TradeStateActive ->
                0

            TradeStateQueued ->
                1

            TradeStateDisavowed ->
                2

            TradeStateDequeueFailed ->
                3

            TradeStateUnrecognized_ v ->
                v


toVoidEncoder : Void -> Encode.Encoder
toVoidEncoder value =
    Encode.int32 <|
        case value of
            Void ->
                0

            VoidUnrecognized_ v ->
                v


toResolutionEncoder : Resolution -> Encode.Encoder
toResolutionEncoder value =
    Encode.int32 <|
        case value of
            ResolutionNoneYet ->
                0

            ResolutionYes ->
                1

            ResolutionNo ->
                2

            ResolutionInvalid ->
                3

            ResolutionUnrecognized_ v ->
                v


toPredictionViewPrivacyEncoder : PredictionViewPrivacy -> Encode.Encoder
toPredictionViewPrivacyEncoder value =
    Encode.int32 <|
        case value of
            PredictionViewPrivacyAnybody ->
                0

            PredictionViewPrivacyAnybodyWithTheLink ->
                1

            PredictionViewPrivacyUnrecognized_ v ->
                v


toPredictionFollowingStatusEncoder : PredictionFollowingStatus -> Encode.Encoder
toPredictionFollowingStatusEncoder value =
    Encode.int32 <|
        case value of
            PredictionFollowingNotFollowing ->
                0

            PredictionFollowingFollowing ->
                1

            PredictionFollowingMandatoryBecauseStaked ->
                2

            PredictionFollowingStatusUnrecognized_ v ->
                v


{-| `AuthToken` encoder
-}
toAuthTokenEncoder : AuthToken -> Encode.Encoder
toAuthTokenEncoder model =
    Encode.message
        [ ( 1, Encode.bytes model.hmacOfRest )
        , ( 7, Encode.string model.owner )
        , ( 5, Encode.double model.mintedUnixtime )
        , ( 6, Encode.double model.expiresUnixtime )
        ]


toEmailFlowStateKindEncoder : EmailFlowStateKind -> ( Int, Encode.Encoder )
toEmailFlowStateKindEncoder model =
    case model of
        EmailFlowStateKindUnstarted value ->
            ( 1, toVoidEncoder value )

        EmailFlowStateKindCodeSent value ->
            ( 2, toEmailFlowStateCodeSentEncoder value )

        EmailFlowStateKindVerified value ->
            ( 3, Encode.string value )


{-| `EmailFlowState` encoder
-}
toEmailFlowStateEncoder : EmailFlowState -> Encode.Encoder
toEmailFlowStateEncoder model =
    Encode.message
        [ Maybe.withDefault ( 0, Encode.none ) <| Maybe.map toEmailFlowStateKindEncoder model.emailFlowStateKind
        ]


toEmailFlowStateCodeSentEncoder : EmailFlowStateCodeSent -> Encode.Encoder
toEmailFlowStateCodeSentEncoder model =
    Encode.message
        [ ( 1, Encode.string model.email )
        , ( 2, (Maybe.withDefault Encode.none << Maybe.map toHashedPasswordEncoder) model.code )
        ]


{-| `HashedPassword` encoder
-}
toHashedPasswordEncoder : HashedPassword -> Encode.Encoder
toHashedPasswordEncoder model =
    Encode.message
        [ ( 1, Encode.bytes model.salt )
        , ( 2, Encode.bytes model.scrypt )
        ]


toLoginTypeEncoder : LoginType -> ( Int, Encode.Encoder )
toLoginTypeEncoder model =
    case model of
        LoginTypeLoginPassword value ->
            ( 7, toHashedPasswordEncoder value )


{-| `GenericUserInfo` encoder
-}
toGenericUserInfoEncoder : GenericUserInfo -> Encode.Encoder
toGenericUserInfoEncoder model =
    Encode.message
        [ ( 10, Encode.string model.emailAddress )
        , ( 5, Encode.dict Encode.string (Maybe.withDefault Encode.none << Maybe.map toGenericUserInfoInvitationEncoder) model.invitations )
        , ( 6, Encode.dict Encode.string (Maybe.withDefault Encode.none << Maybe.map toRelationshipEncoder) model.relationships )
        , Maybe.withDefault ( 0, Encode.none ) <| Maybe.map toLoginTypeEncoder model.loginType
        ]


toGenericUserInfoInvitationEncoder : GenericUserInfoInvitation -> Encode.Encoder
toGenericUserInfoInvitationEncoder model =
    Encode.message
        []


{-| `Relationship` encoder
-}
toRelationshipEncoder : Relationship -> Encode.Encoder
toRelationshipEncoder model =
    Encode.message
        [ ( 1, Encode.bool model.trustsYou )
        , ( 2, Encode.bool model.trustedByYou )
        ]


{-| `UsernameInfo` encoder
-}
toUsernameInfoEncoder : UsernameInfo -> Encode.Encoder
toUsernameInfoEncoder model =
    Encode.message
        [ ( 1, (Maybe.withDefault Encode.none << Maybe.map toGenericUserInfoEncoder) model.info )
        , ( 2, (Maybe.withDefault Encode.none << Maybe.map toHashedPasswordEncoder) model.password )
        ]


{-| `EmailAttempt` encoder
-}
toEmailAttemptEncoder : EmailAttempt -> Encode.Encoder
toEmailAttemptEncoder model =
    Encode.message
        [ ( 1, Encode.double model.unixtime )
        , ( 2, Encode.bool model.succeeded )
        ]


{-| `ResolutionEvent` encoder
-}
toResolutionEventEncoder : ResolutionEvent -> Encode.Encoder
toResolutionEventEncoder model =
    Encode.message
        [ ( 4, Encode.double model.unixtime )
        , ( 2, toResolutionEncoder model.resolution )
        , ( 3, Encode.string model.notes )
        , ( 5, (Maybe.withDefault Encode.none << Maybe.map toResolutionEventEncoder) (unwrapResolutionEventPriorRevision model.priorRevision) )
        ]


{-| `Trade` encoder
-}
toTradeEncoder : Trade -> Encode.Encoder
toTradeEncoder model =
    Encode.message
        [ ( 7, Encode.string model.bettor )
        , ( 2, Encode.bool model.bettorIsASkeptic )
        , ( 3, Encode.uint32 model.bettorStakeCents )
        , ( 4, Encode.uint32 model.creatorStakeCents )
        , ( 6, Encode.double model.transactedUnixtime )
        , ( 8, Encode.double model.updatedUnixtime )
        , ( 9, Encode.string model.notes )
        , ( 10, toTradeStateEncoder model.state )
        ]


{-| `Empty` encoder
-}
toEmptyEncoder : Empty -> Encode.Encoder
toEmptyEncoder model =
    Encode.message
        []


{-| `ErrorResponse` encoder
-}
toErrorResponseEncoder : ErrorResponse -> Encode.Encoder
toErrorResponseEncoder model =
    Encode.message
        [ ( 1, Encode.string model.catchall )
        ]


{-| `WhoamiRequest` encoder
-}
toWhoamiRequestEncoder : WhoamiRequest -> Encode.Encoder
toWhoamiRequestEncoder model =
    Encode.message
        []


{-| `WhoamiResponse` encoder
-}
toWhoamiResponseEncoder : WhoamiResponse -> Encode.Encoder
toWhoamiResponseEncoder model =
    Encode.message
        [ ( 1, Encode.string model.username )
        ]


{-| `SignOutRequest` encoder
-}
toSignOutRequestEncoder : SignOutRequest -> Encode.Encoder
toSignOutRequestEncoder model =
    Encode.message
        []


{-| `SignOutResponse` encoder
-}
toSignOutResponseEncoder : SignOutResponse -> Encode.Encoder
toSignOutResponseEncoder model =
    Encode.message
        []


{-| `AuthSuccess` encoder
-}
toAuthSuccessEncoder : AuthSuccess -> Encode.Encoder
toAuthSuccessEncoder model =
    Encode.message
        [ ( 1, (Maybe.withDefault Encode.none << Maybe.map toAuthTokenEncoder) model.token )
        , ( 2, (Maybe.withDefault Encode.none << Maybe.map toGenericUserInfoEncoder) model.userInfo )
        ]


{-| `SendVerificationEmailRequest` encoder
-}
toSendVerificationEmailRequestEncoder : SendVerificationEmailRequest -> Encode.Encoder
toSendVerificationEmailRequestEncoder model =
    Encode.message
        [ ( 1, Encode.string model.emailAddress )
        ]


{-| `RegisterUsernameRequest` encoder
-}
toRegisterUsernameRequestEncoder : RegisterUsernameRequest -> Encode.Encoder
toRegisterUsernameRequestEncoder model =
    Encode.message
        [ ( 1, Encode.string model.username )
        , ( 2, Encode.string model.password )
        , ( 3, Encode.string model.proofOfEmailToken )
        ]


{-| `LogInUsernameRequest` encoder
-}
toLogInUsernameRequestEncoder : LogInUsernameRequest -> Encode.Encoder
toLogInUsernameRequestEncoder model =
    Encode.message
        [ ( 1, Encode.string model.username )
        , ( 2, Encode.string model.password )
        ]


{-| `CertaintyRange` encoder
-}
toCertaintyRangeEncoder : CertaintyRange -> Encode.Encoder
toCertaintyRangeEncoder model =
    Encode.message
        [ ( 1, Encode.float model.low )
        , ( 2, Encode.float model.high )
        ]


{-| `CreatePredictionRequest` encoder
-}
toCreatePredictionRequestEncoder : CreatePredictionRequest -> Encode.Encoder
toCreatePredictionRequestEncoder model =
    Encode.message
        [ ( 2, Encode.string model.prediction )
        , ( 3, toPredictionViewPrivacyEncoder model.viewPrivacy )
        , ( 4, (Maybe.withDefault Encode.none << Maybe.map toCertaintyRangeEncoder) model.certainty )
        , ( 5, Encode.uint32 model.maximumStakeCents )
        , ( 6, Encode.uint32 model.openSeconds )
        , ( 7, Encode.string model.specialRules )
        , ( 9, Encode.double model.resolvesAtUnixtime )
        ]


{-| `CreatePredictionResponse` encoder
-}
toCreatePredictionResponseEncoder : CreatePredictionResponse -> Encode.Encoder
toCreatePredictionResponseEncoder model =
    Encode.message
        [ ( 1, Encode.string model.newPredictionId )
        ]


{-| `GetPredictionRequest` encoder
-}
toGetPredictionRequestEncoder : GetPredictionRequest -> Encode.Encoder
toGetPredictionRequestEncoder model =
    Encode.message
        [ ( 2, Encode.string model.predictionId )
        ]


{-| `UserPredictionView` encoder
-}
toUserPredictionViewEncoder : UserPredictionView -> Encode.Encoder
toUserPredictionViewEncoder model =
    Encode.message
        [ ( 1, Encode.string model.prediction )
        , ( 2, (Maybe.withDefault Encode.none << Maybe.map toCertaintyRangeEncoder) model.certainty )
        , ( 3, Encode.uint32 model.maximumStakeCents )
        , ( 4, Encode.uint32 model.remainingStakeCentsVsBelievers )
        , ( 5, Encode.uint32 model.remainingStakeCentsVsSkeptics )
        , ( 13, Encode.double model.createdUnixtime )
        , ( 14, Encode.double model.closesUnixtime )
        , ( 8, Encode.string model.specialRules )
        , ( 9, Encode.string model.creator )
        , ( 17, (Maybe.withDefault Encode.none << Maybe.map toResolutionEventEncoder) model.resolution )
        , ( 11, Encode.list toTradeEncoder model.yourTrades )
        , ( 15, Encode.double model.resolvesAtUnixtime )
        , ( 18, toPredictionFollowingStatusEncoder model.yourFollowingStatus )
        ]


{-| `ListMyStakesRequest` encoder
-}
toListMyStakesRequestEncoder : ListMyStakesRequest -> Encode.Encoder
toListMyStakesRequestEncoder model =
    Encode.message
        []


{-| `PredictionsById` encoder
-}
toPredictionsByIdEncoder : PredictionsById -> Encode.Encoder
toPredictionsByIdEncoder model =
    Encode.message
        [ ( 1, Encode.dict Encode.string (Maybe.withDefault Encode.none << Maybe.map toUserPredictionViewEncoder) model.predictions )
        ]


{-| `ListPredictionsRequest` encoder
-}
toListPredictionsRequestEncoder : ListPredictionsRequest -> Encode.Encoder
toListPredictionsRequestEncoder model =
    Encode.message
        [ ( 2, Encode.string model.creator )
        ]


{-| `FollowRequest` encoder
-}
toFollowRequestEncoder : FollowRequest -> Encode.Encoder
toFollowRequestEncoder model =
    Encode.message
        [ ( 1, Encode.string model.predictionId )
        , ( 2, Encode.bool model.follow )
        ]


{-| `StakeRequest` encoder
-}
toStakeRequestEncoder : StakeRequest -> Encode.Encoder
toStakeRequestEncoder model =
    Encode.message
        [ ( 2, Encode.string model.predictionId )
        , ( 3, Encode.bool model.bettorIsASkeptic )
        , ( 4, Encode.uint32 model.bettorStakeCents )
        ]


{-| `ResolveRequest` encoder
-}
toResolveRequestEncoder : ResolveRequest -> Encode.Encoder
toResolveRequestEncoder model =
    Encode.message
        [ ( 1, Encode.string model.predictionId )
        , ( 2, toResolutionEncoder model.resolution )
        , ( 3, Encode.string model.notes )
        ]


{-| `SetTrustedRequest` encoder
-}
toSetTrustedRequestEncoder : SetTrustedRequest -> Encode.Encoder
toSetTrustedRequestEncoder model =
    Encode.message
        [ ( 3, Encode.string model.who )
        , ( 2, Encode.bool model.trusted )
        ]


{-| `GetUserRequest` encoder
-}
toGetUserRequestEncoder : GetUserRequest -> Encode.Encoder
toGetUserRequestEncoder model =
    Encode.message
        [ ( 2, Encode.string model.who )
        ]


{-| `ChangePasswordRequest` encoder
-}
toChangePasswordRequestEncoder : ChangePasswordRequest -> Encode.Encoder
toChangePasswordRequestEncoder model =
    Encode.message
        [ ( 1, Encode.string model.oldPassword )
        , ( 2, Encode.string model.newPassword )
        ]


{-| `GetSettingsRequest` encoder
-}
toGetSettingsRequestEncoder : GetSettingsRequest -> Encode.Encoder
toGetSettingsRequestEncoder model =
    Encode.message
        [ ( 1, Encode.list Encode.string model.includeRelationshipsWithUsers )
        ]


{-| `SendInvitationRequest` encoder
-}
toSendInvitationRequestEncoder : SendInvitationRequest -> Encode.Encoder
toSendInvitationRequestEncoder model =
    Encode.message
        [ ( 1, Encode.string model.recipient )
        ]


{-| `CheckInvitationRequest` encoder
-}
toCheckInvitationRequestEncoder : CheckInvitationRequest -> Encode.Encoder
toCheckInvitationRequestEncoder model =
    Encode.message
        [ ( 1, Encode.string model.nonce )
        ]


{-| `CheckInvitationResponse` encoder
-}
toCheckInvitationResponseEncoder : CheckInvitationResponse -> Encode.Encoder
toCheckInvitationResponseEncoder model =
    Encode.message
        [ ( 1, Encode.string model.inviter )
        , ( 2, Encode.string model.recipient )
        ]


{-| `AcceptInvitationRequest` encoder
-}
toAcceptInvitationRequestEncoder : AcceptInvitationRequest -> Encode.Encoder
toAcceptInvitationRequestEncoder model =
    Encode.message
        [ ( 1, Encode.string model.nonce )
        ]


{-| `SavedCreatedPredictionFormState` encoder
-}
toSavedCreatedPredictionFormStateEncoder : SavedCreatedPredictionFormState -> Encode.Encoder
toSavedCreatedPredictionFormStateEncoder model =
    Encode.message
        [ ( 1, Encode.string model.predictionField )
        , ( 2, Encode.string model.resolvesAtField )
        , ( 3, Encode.string model.stakeField )
        , ( 4, Encode.string model.lowPField )
        , ( 5, Encode.string model.highPField )
        , ( 6, Encode.string model.openForUnitField )
        , ( 7, Encode.string model.openForSecondsField )
        , ( 9, Encode.string model.viewPrivacyField )
        , ( 8, Encode.string model.specialRulesField )
        ]



-- SETTERS


setHmacOfRest : a -> { b | hmacOfRest : a } -> { b | hmacOfRest : a }
setHmacOfRest value model =
    { model | hmacOfRest = value }


setOwner : a -> { b | owner : a } -> { b | owner : a }
setOwner value model =
    { model | owner = value }


setMintedUnixtime : a -> { b | mintedUnixtime : a } -> { b | mintedUnixtime : a }
setMintedUnixtime value model =
    { model | mintedUnixtime = value }


setExpiresUnixtime : a -> { b | expiresUnixtime : a } -> { b | expiresUnixtime : a }
setExpiresUnixtime value model =
    { model | expiresUnixtime = value }


setEmailFlowStateKind : a -> { b | emailFlowStateKind : a } -> { b | emailFlowStateKind : a }
setEmailFlowStateKind value model =
    { model | emailFlowStateKind = value }


setEmail : a -> { b | email : a } -> { b | email : a }
setEmail value model =
    { model | email = value }


setCode : a -> { b | code : a } -> { b | code : a }
setCode value model =
    { model | code = value }


setSalt : a -> { b | salt : a } -> { b | salt : a }
setSalt value model =
    { model | salt = value }


setScrypt : a -> { b | scrypt : a } -> { b | scrypt : a }
setScrypt value model =
    { model | scrypt = value }


setEmailAddress : a -> { b | emailAddress : a } -> { b | emailAddress : a }
setEmailAddress value model =
    { model | emailAddress = value }


setInvitations : a -> { b | invitations : a } -> { b | invitations : a }
setInvitations value model =
    { model | invitations = value }


setRelationships : a -> { b | relationships : a } -> { b | relationships : a }
setRelationships value model =
    { model | relationships = value }


setLoginType : a -> { b | loginType : a } -> { b | loginType : a }
setLoginType value model =
    { model | loginType = value }


setTrustsYou : a -> { b | trustsYou : a } -> { b | trustsYou : a }
setTrustsYou value model =
    { model | trustsYou = value }


setTrustedByYou : a -> { b | trustedByYou : a } -> { b | trustedByYou : a }
setTrustedByYou value model =
    { model | trustedByYou = value }


setInfo : a -> { b | info : a } -> { b | info : a }
setInfo value model =
    { model | info = value }


setPassword : a -> { b | password : a } -> { b | password : a }
setPassword value model =
    { model | password = value }


setUnixtime : a -> { b | unixtime : a } -> { b | unixtime : a }
setUnixtime value model =
    { model | unixtime = value }


setSucceeded : a -> { b | succeeded : a } -> { b | succeeded : a }
setSucceeded value model =
    { model | succeeded = value }


setResolution : a -> { b | resolution : a } -> { b | resolution : a }
setResolution value model =
    { model | resolution = value }


setNotes : a -> { b | notes : a } -> { b | notes : a }
setNotes value model =
    { model | notes = value }


setPriorRevision : a -> { b | priorRevision : a } -> { b | priorRevision : a }
setPriorRevision value model =
    { model | priorRevision = value }


setBettor : a -> { b | bettor : a } -> { b | bettor : a }
setBettor value model =
    { model | bettor = value }


setBettorIsASkeptic : a -> { b | bettorIsASkeptic : a } -> { b | bettorIsASkeptic : a }
setBettorIsASkeptic value model =
    { model | bettorIsASkeptic = value }


setBettorStakeCents : a -> { b | bettorStakeCents : a } -> { b | bettorStakeCents : a }
setBettorStakeCents value model =
    { model | bettorStakeCents = value }


setCreatorStakeCents : a -> { b | creatorStakeCents : a } -> { b | creatorStakeCents : a }
setCreatorStakeCents value model =
    { model | creatorStakeCents = value }


setTransactedUnixtime : a -> { b | transactedUnixtime : a } -> { b | transactedUnixtime : a }
setTransactedUnixtime value model =
    { model | transactedUnixtime = value }


setUpdatedUnixtime : a -> { b | updatedUnixtime : a } -> { b | updatedUnixtime : a }
setUpdatedUnixtime value model =
    { model | updatedUnixtime = value }


setState : a -> { b | state : a } -> { b | state : a }
setState value model =
    { model | state = value }


setCatchall : a -> { b | catchall : a } -> { b | catchall : a }
setCatchall value model =
    { model | catchall = value }


setUsername : a -> { b | username : a } -> { b | username : a }
setUsername value model =
    { model | username = value }


setToken : a -> { b | token : a } -> { b | token : a }
setToken value model =
    { model | token = value }


setUserInfo : a -> { b | userInfo : a } -> { b | userInfo : a }
setUserInfo value model =
    { model | userInfo = value }


setProofOfEmailToken : a -> { b | proofOfEmailToken : a } -> { b | proofOfEmailToken : a }
setProofOfEmailToken value model =
    { model | proofOfEmailToken = value }


setLow : a -> { b | low : a } -> { b | low : a }
setLow value model =
    { model | low = value }


setHigh : a -> { b | high : a } -> { b | high : a }
setHigh value model =
    { model | high = value }


setPrediction : a -> { b | prediction : a } -> { b | prediction : a }
setPrediction value model =
    { model | prediction = value }


setViewPrivacy : a -> { b | viewPrivacy : a } -> { b | viewPrivacy : a }
setViewPrivacy value model =
    { model | viewPrivacy = value }


setCertainty : a -> { b | certainty : a } -> { b | certainty : a }
setCertainty value model =
    { model | certainty = value }


setMaximumStakeCents : a -> { b | maximumStakeCents : a } -> { b | maximumStakeCents : a }
setMaximumStakeCents value model =
    { model | maximumStakeCents = value }


setOpenSeconds : a -> { b | openSeconds : a } -> { b | openSeconds : a }
setOpenSeconds value model =
    { model | openSeconds = value }


setSpecialRules : a -> { b | specialRules : a } -> { b | specialRules : a }
setSpecialRules value model =
    { model | specialRules = value }


setResolvesAtUnixtime : a -> { b | resolvesAtUnixtime : a } -> { b | resolvesAtUnixtime : a }
setResolvesAtUnixtime value model =
    { model | resolvesAtUnixtime = value }


setNewPredictionId : a -> { b | newPredictionId : a } -> { b | newPredictionId : a }
setNewPredictionId value model =
    { model | newPredictionId = value }


setPredictionId : a -> { b | predictionId : a } -> { b | predictionId : a }
setPredictionId value model =
    { model | predictionId = value }


setRemainingStakeCentsVsBelievers : a -> { b | remainingStakeCentsVsBelievers : a } -> { b | remainingStakeCentsVsBelievers : a }
setRemainingStakeCentsVsBelievers value model =
    { model | remainingStakeCentsVsBelievers = value }


setRemainingStakeCentsVsSkeptics : a -> { b | remainingStakeCentsVsSkeptics : a } -> { b | remainingStakeCentsVsSkeptics : a }
setRemainingStakeCentsVsSkeptics value model =
    { model | remainingStakeCentsVsSkeptics = value }


setCreatedUnixtime : a -> { b | createdUnixtime : a } -> { b | createdUnixtime : a }
setCreatedUnixtime value model =
    { model | createdUnixtime = value }


setClosesUnixtime : a -> { b | closesUnixtime : a } -> { b | closesUnixtime : a }
setClosesUnixtime value model =
    { model | closesUnixtime = value }


setCreator : a -> { b | creator : a } -> { b | creator : a }
setCreator value model =
    { model | creator = value }


setYourTrades : a -> { b | yourTrades : a } -> { b | yourTrades : a }
setYourTrades value model =
    { model | yourTrades = value }


setYourFollowingStatus : a -> { b | yourFollowingStatus : a } -> { b | yourFollowingStatus : a }
setYourFollowingStatus value model =
    { model | yourFollowingStatus = value }


setPredictions : a -> { b | predictions : a } -> { b | predictions : a }
setPredictions value model =
    { model | predictions = value }


setFollow : a -> { b | follow : a } -> { b | follow : a }
setFollow value model =
    { model | follow = value }


setWho : a -> { b | who : a } -> { b | who : a }
setWho value model =
    { model | who = value }


setTrusted : a -> { b | trusted : a } -> { b | trusted : a }
setTrusted value model =
    { model | trusted = value }


setOldPassword : a -> { b | oldPassword : a } -> { b | oldPassword : a }
setOldPassword value model =
    { model | oldPassword = value }


setNewPassword : a -> { b | newPassword : a } -> { b | newPassword : a }
setNewPassword value model =
    { model | newPassword = value }


setIncludeRelationshipsWithUsers : a -> { b | includeRelationshipsWithUsers : a } -> { b | includeRelationshipsWithUsers : a }
setIncludeRelationshipsWithUsers value model =
    { model | includeRelationshipsWithUsers = value }


setRecipient : a -> { b | recipient : a } -> { b | recipient : a }
setRecipient value model =
    { model | recipient = value }


setNonce : a -> { b | nonce : a } -> { b | nonce : a }
setNonce value model =
    { model | nonce = value }


setInviter : a -> { b | inviter : a } -> { b | inviter : a }
setInviter value model =
    { model | inviter = value }


setPredictionField : a -> { b | predictionField : a } -> { b | predictionField : a }
setPredictionField value model =
    { model | predictionField = value }


setResolvesAtField : a -> { b | resolvesAtField : a } -> { b | resolvesAtField : a }
setResolvesAtField value model =
    { model | resolvesAtField = value }


setStakeField : a -> { b | stakeField : a } -> { b | stakeField : a }
setStakeField value model =
    { model | stakeField = value }


setLowPField : a -> { b | lowPField : a } -> { b | lowPField : a }
setLowPField value model =
    { model | lowPField = value }


setHighPField : a -> { b | highPField : a } -> { b | highPField : a }
setHighPField value model =
    { model | highPField = value }


setOpenForUnitField : a -> { b | openForUnitField : a } -> { b | openForUnitField : a }
setOpenForUnitField value model =
    { model | openForUnitField = value }


setOpenForSecondsField : a -> { b | openForSecondsField : a } -> { b | openForSecondsField : a }
setOpenForSecondsField value model =
    { model | openForSecondsField = value }


setViewPrivacyField : a -> { b | viewPrivacyField : a } -> { b | viewPrivacyField : a }
setViewPrivacyField value model =
    { model | viewPrivacyField = value }


setSpecialRulesField : a -> { b | specialRulesField : a } -> { b | specialRulesField : a }
setSpecialRulesField value model =
    { model | specialRulesField = value }
